generated devise gem
jarencudilla/pc-builder-app pull request #2
Opened 2021-07-12 13:13 UTC by EliezerAmbion

## Pull Request

#### generated devise gem

## The Story
- Generated the devise gem
- Installed the bootstrap css framework
- Added a navbar
- Added custom field in the user table (username)

## Screenshots
![nav](https://user-images.githubusercontent.com/57052385/125292187-cbbf4500-e354-11eb-8850-1930d98bb7fb.png)

## References
https://www.youtube.com/watch?v=9K5YvsrKBRk

2021-07-12 13:19 UTC, jarencudilla commented
Nice one!

2021-07-12 13:22 UTC, jarencudilla approved these changes
Thank you for setting bootstrap and devise

2021-07-12 13:23 UTC, DanielCadiz approved these changes

2021-07-12 13:31 UTC, AdrianIlaga approved these changes

2021-07-13 00:37 UTC, analyn-cajocson commented on app/views/layouts/shared/_flash.html.erb
> +<% end %>
add new line

2021-07-13 00:38 UTC, analyn-cajocson requested changes

2021-07-13 00:38 UTC, analyn-cajocson commented on app/views/shared/_navbar.html.erb
> +</nav>
add new line

2021-07-13 04:05 UTC, analyn-cajocson approved these changes

2021-07-13 04:18 UTC, merged